package:
  name: distributions
  version: "2.2.1"

source:
  path: ../../

requirements:
  build:
    - cmake
    - cython 0.23.*
    - eigen >=2.91.0
    - libprotobuf 2.6.1
    - numpy 1.11.*
    - python 2.7.*
    - pyflakes
  run:
    - eigen >=2.91.0
    - numpy 1.11.*
    - python 2.7.*
    - libprotobuf 2.6.1
    - simplejson

test:
  imports:
    - distributions
    - distributions.lp
    - distributions.lp.models
    - distributions.lp.models.bb

about:
  home: https://github.com/posterior/distributions
